on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

name: Create BluedPanel Release

jobs:
  release:
    name: ubuntu-20.04
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Build assets
        run: |
          yarn install
          yarn run build:production
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REF: ${{ github.ref }}
        
      - name: Build assets
        run: |
          yarn install
          yarn run build:production
      - name: Create release archive
        run: |
          rm -rf node_modules/ test/ codecov.yml CODE_OF_CONDUCT.md CONTRIBUTING.md phpunit.xml Vagrantfile
          tar -czf panel.tar.gz * .env.example .eslintignore .eslintrc.js
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ steps.extract_changelog.outputs.version_name }}
          draft: true
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}

      - name: Upload binary
        id: upload-release-archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: panel.tar.gz
          asset_name: panel.tar.gz
          asset_content_type: application/gzip
